### ISSUE TITLE
TODO - LAB GUIDE

### ISSUE THREAD

**Issue by liks79** [aws-kr-tnc/moving-to-serverless-renew#85]
## LAB01
- [ ] 그림수정필요 : /images/lab01-frontend-project-structure.png
- [ ] 그림수정필요: ./images/lab01-backend-project-structure.png
- [ ] Step 30. Admin Swagger 추가..

## LAB02
- [ ] 그림 추가 필요 (s3 frontend): ./images/lab02-task1-cf-diagram.png
- [ ] Healthcheck 에서 admin/health_chek 으로 변환 필요
